import { classicBasePlacements } from '@chessforge/engine';
import type { Deck, OwnedCard } from './types.js';

export const STARTER_COLLECTION: OwnedCard[] = [
  { defId: 'king', count: 1 },
  { defId: 'warden', count: 1 },
  { defId: 'anchor', count: 1 },
  { defId: 'hierophant', count: 1 },
  { defId: 'dynast', count: 1 },
  { defId: 'queen', count: 1 },
  { defId: 'regent', count: 1 },
  { defId: 'cryomancer', count: 1 },
  { defId: 'patron', count: 1 },
  { defId: 'rook', count: 2 },
  { defId: 'sprinter', count: 1 },
  { defId: 'sentry', count: 1 },
  { defId: 'aegis', count: 1 },
  { defId: 'bishop', count: 2 },
  { defId: 'chaplain', count: 1 },
  { defId: 'exchanger', count: 1 },
  { defId: 'bastion', count: 1 },
  { defId: 'knight', count: 2 },
  { defId: 'lancer', count: 1 },
  { defId: 'outrider', count: 1 },
  { defId: 'courser', count: 1 },
  { defId: 'pawn', count: 8 },
  { defId: 'skirmisher', count: 2 },
  { defId: 'ironclad', count: 2 },
  { defId: 'spearman', count: 2 },
  { defId: 'ram', count: 2 },
  { defId: 'bristling', count: 2 },
  { defId: 'cleric', count: 1 },
  { defId: 'quagmire', count: 1 },
  { defId: 'sluggard', count: 1 },
  { defId: 'hexer', count: 1 },
  { defId: 'wayfarer', count: 1 },
  { defId: 'escort', count: 1 },
  { defId: 'juggernaut', count: 1 },
  { defId: 'thornqueen', count: 1 },
  { defId: 'veilqueen', count: 1 },
  { defId: 'hearteater', count: 1 },
  { defId: 'reaver', count: 1 },
  { defId: 'javelin', count: 1 },
  { defId: 'judge', count: 1 },
];

export const STARTER_DECK: Deck = {
  id: 'starter',
  name: 'Классический строй',
  placements: classicBasePlacements(),
};
